name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Push events to tags starting with v (v0.0.1, v1.0.0, etc)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow
          
      - name: Build macOS package
        run: |
          # Run our new direct build script
          bash scripts/direct_build.sh
          
      - name: Create DMG installer
        run: |
          # Use our new DMG creation script
          python create_dmg.py
          
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: |
            UCI-ClusterManager-*.dmg
            dist/UCI-ClusterManager.app

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow
          
      - name: Build Windows package
        run: |
          # Use PyInstaller directly for now
          python -m PyInstaller --name="UCI-ClusterManager" ^
            --windowed ^
            --add-data="my_hpc_app/resources;resources" ^
            --add-data="my_hpc_app/modules;modules" ^
            --add-data="my_hpc_app/ui;ui" ^
            --hidden-import=pexpect ^
            --hidden-import=paramiko ^
            --hidden-import=cryptography ^
            --hidden-import=bcrypt ^
            --hidden-import=PyQt5 ^
            --hidden-import=PyQt5.QtWidgets ^
            --hidden-import=PyQt5.QtCore ^
            --hidden-import=PyQt5.QtGui ^
            --hidden-import=requests ^
            --hidden-import=packaging ^
            --hidden-import=packaging.version ^
            --icon="my_hpc_app/resources/icon.ico" ^
            "my_hpc_app/main.py"
          
      - name: Create Windows installer
        run: |
          # Basic ZIP archive for now - can be improved later
          Compress-Archive -Path dist/UCI-ClusterManager/* -DestinationPath "UCI-ClusterManager-${{ github.ref_name }}-windows.zip"
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: UCI-ClusterManager-*.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libgl1-mesa-dev fakeroot
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow
          
      - name: Build Linux package
        run: |
          # Use PyInstaller directly 
          python -m PyInstaller --name="UCI-ClusterManager" \
            --windowed \
            --add-data="my_hpc_app/resources:resources" \
            --add-data="my_hpc_app/modules:modules" \
            --add-data="my_hpc_app/ui:ui" \
            --hidden-import=pexpect \
            --hidden-import=paramiko \
            --hidden-import=cryptography \
            --hidden-import=bcrypt \
            --hidden-import=PyQt5 \
            --hidden-import=PyQt5.QtWidgets \
            --hidden-import=PyQt5.QtCore \
            --hidden-import=PyQt5.QtGui \
            --hidden-import=requests \
            --hidden-import=packaging \
            --hidden-import=packaging.version \
            --icon="my_hpc_app/resources/icon.ico" \
            "my_hpc_app/main.py"
          
      - name: Create Debian package
        run: |
          mkdir -p dist/deb-package/DEBIAN
          mkdir -p dist/deb-package/usr/local/bin
          mkdir -p dist/deb-package/usr/share/applications
          mkdir -p dist/deb-package/usr/share/icons/hicolor/256x256/apps
          
          # Copy executable files
          cp -r dist/UCI-ClusterManager/* dist/deb-package/usr/local/bin/
          
          # Create desktop file
          echo "[Desktop Entry]
          Name=UCI-ClusterManager
          Comment=A graphical tool for managing UCI HPC cluster resources
          Exec=/usr/local/bin/UCI-ClusterManager
          Icon=/usr/share/icons/hicolor/256x256/apps/uci-clustermanager.png
          Terminal=false
          Type=Application
          Categories=Utility;Science;" > dist/deb-package/usr/share/applications/uci-clustermanager.desktop
          
          # Copy icon
          cp my_hpc_app/resources/icon.png dist/deb-package/usr/share/icons/hicolor/256x256/apps/uci-clustermanager.png
          
          # Create control file
          VERSION=$(echo ${{ github.ref_name }} | sed 's/v//')
          echo "Package: uci-clustermanager
          Version: ${VERSION:-0.0.1}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libc6, libgl1
          Maintainer: Song Liangyu
          Description: UCI-ClusterManager
           A graphical tool for managing UCI HPC cluster resources
           including job management, node status, and VSCode integration." > dist/deb-package/DEBIAN/control
          
          # Build deb package
          fakeroot dpkg-deb --build dist/deb-package "UCI-ClusterManager-${VERSION:-0.0.1}-linux.deb"
          
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: UCI-ClusterManager-*.deb

  create-release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: UCI-ClusterManager ${{ github.ref_name }}
          body_path: RELEASE_NOTES_${{ github.ref_name }}.md
          draft: false
          prerelease: false
          files: |
            artifacts/macos-artifacts/UCI-ClusterManager-*.dmg
            artifacts/windows-artifacts/UCI-ClusterManager-*.zip
            artifacts/linux-artifacts/UCI-ClusterManager-*.deb
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 